### PR TITLE
Refactored repo layout

### PR DESCRIPTION
**Pull request by cschuchardt88**
# Change Log
- Changed layout

Made it easier for you to develop. Ill update the code later. We are missing packages on `nuget.org` for `neo-modules` on new release. So I'll set-up this repo for you. Than I'll make the changes for you in https://github.com/neo-project/neo/pull/3225#issuecomment-2105612016

If you don't want this just close this PR.

### CODE REVIEW

**Comment by Hecate2** [comment]
Please allow me to think twice on having a standalone Fairy directory, and making the dependency changes in Fairy.csproj. My original setup encourages users to clone this repo stupidly simply into neo-modules, and build and debug the whole source codes of Neo, including the RpcServer and Neo.Json.

**Comment by cschuchardt88** [comment]
Why do you did that though? You can just use the `nuget` packages. It can very confusing for someone that doesn't use any code. that just expects you to open and compile/build.

**Comment by Hecate2** [comment]
Because nuget packages cannot be debugged, and there can be weird exceptions from anywhere. I do need to debug with source codes to capture errors.

**Comment by cschuchardt88** [comment]
they have debug information in the nuget package. Just tell your IDE to enable nuget package source.
image

**Comment by Hecate2** [comment]
> they have debug information in the nuget package. Just tell your IDE to enable nuget package source. 

I think this is still making difficulties for running Fairy with any version and any commit of Neo source codes... I made Fairy for not only testing contracts, but evaluating contracts at any live version of blockchain.

**Comment by cschuchardt88** [comment]
OK. Just thought your `plugin` was for `neo-cli` as a plugin.

**Pull request closed without merging**
